server:
  port: 8081
  servlet:
    context-path: /coe

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/alumnos
    username: ${USER}
    password: ${PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update







