
spring:
  application:
    name: config-service

  cloud:
    config:
      server:
        git:
          uri: https://github.com/AdjanyArmenta/escolar-project.git
          search-paths: config-data
          default-label: main
#          username: AdjanyArmenta
#          password:
server:
  port: 8071

